sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
script:
  - make
  - make test
  - ./build/sePrepTests
  - ./build/sePrep -test -error

env:
  global:
    # Token provided in settings of codecov
    # - CODECOV_TOKEN=:bf2b7da2-833f-47d6-8660-d149faed8097
    - CODECOV_TOKEN="bf2b7da2-833f-47d6-8660-d149faed8097"
after_success:
  # Run bash script to upload code coverage files
  - bash <(curl -s https://codecov.io/bash)
  - make clean
