sudo: false
language: cpp, java
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
before_install:
  - chmod +x ./leetCodeSolutionsKotlin/gradlew
  - chmod +x ./leetCodeSolutionsKotlin/gradle/wrapper/gradle-wrapper.jar
script:
  - cmake .
  - make
  - ./bin/solutions -test
  - ./bin/unit_tests
  - cd leetCodeSolutionsKotlin
  - ./gradlew build

env:
  global:
    # Token provided in settings of codecov
    # - CODECOV_TOKEN=:bf2b7da2-833f-47d6-8660-d149faed8097
    - CODECOV_TOKEN="bf2b7da2-833f-47d6-8660-d149faed8097"
after_success:
  # Run bash script to upload code coverage files
  - bash <(curl -s https://codecov.io/bash)
  - make clean
