sudo: false

matrix:
  include:
    - language: cpp
      compiler:
        - gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
      install:
      - "[ $CXX = g++ ] && export CXX=g++-7 || true"
      script:
        - cd leetCodeSolutionsCpp
        - cmake .
        - make
        - ./bin/solutions -test
        - ./bin/unit_tests
      after_success:
        - bash <(curl -s https://codecov.io/bash) -R ../
        - make clean
    - language: java
      script:
        - cd leetCodeSolutionsKotlin
        - ./gradlew build
      after_success:
        - bash <(curl -s https://codecov.io/bash) -R ./src/main/kotlin
    - language: python
      python:
        - "3.6"
      install:
        - "pip3 install pytest==5.3.2"
        - "pip3 install codecov==2.0.15"
        - "pip3 install pytest-cov==2.8.1"
      script:
        - cd leetCodeSolutionsPython
        - python3 -m pytest --cov-report term --cov .
      after_success:
        - bash <(curl -s https://codecov.io/bash) -R .

before_install:
  - chmod +x ./leetCodeSolutionsKotlin/gradlew
  - chmod +x ./leetCodeSolutionsKotlin/gradle/wrapper/gradle-wrapper.jar
env:
  global:
    # Token provided in settings of codecov
    # - CODECOV_TOKEN=:bf2b7da2-833f-47d6-8660-d149faed8097
    - CODECOV_TOKEN="bf2b7da2-833f-47d6-8660-d149faed8097"
  
